config/routes.rb
Catalogo::Application.routes.draw do
  resources :images

  resources :products

  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :products
  
  
  def to_s
      name
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  belongs_to :product
  has_attached_file :image, :styles => { :medium => "300x300>", :small => "48x48>", :thumb => "100x100>" }
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
    has_many :images

    has_attached_file :image, :styles => { :medium => "300x300>", :small => "48x48>", :thumb => "100x100>" }

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
     @categories = Category.all
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(categories_path, :notice => 'Category was successfully created.') }
       # format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
         format.html { redirect_to(categories_path, :notice => 'Category was successfully updated.') }
       # format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
   uses_tiny_mce
  def index
    @products = Product.all
    
    
    if ((params[:cat]) == nil)

    @products = Product.paginate :per_page => 5, :page => params[:page]
     else
     #  @products = Product.paginate :per_page => 5, :page => params[:page], :conditions => 'products.category_id=' + params[:cat]
    #   @cats = Category.paginate :per_page => 5, :page => params[:page],  :conditions => 'categories.id=' + params[:cat]
    end
    
    
    @categories = Category.all
    if ((params[:cat])!=nil)
    
    @category = Category.find(params[:cat])
   end
   # @products = Product.all, :include => "images"
 
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])
    @categories = Category.all
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
    @images = Productsimage.where(:id_product =>@product.id)
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_categories.html.erb
<div class="titinterior">
       <h1> PRODUCTOS</h1>
     </div>

 <% @categories.each do |category| %>  
   <div class="btn_menu"><p class="txtmenu"><%= link_to category.name, :action => 'index', :cat => category.id %></p></div>
 <% end %>




<% 
 # link_to act_nombre, :controller => 'actividad', :action => 'show',
#:id => act_id
%>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.text_field :name, :class => 'vermas' %>
  </div>
  <div>
<div>
<%= f.submit 'guardar', :class => 'vermas' %>
  </div>
<% end %>

app/views/categories/_listado_edit.html.erb
<div class="titinterior">
       <h1> PRODUCTOS</h1>
     </div>

 <% @categories.each do |category| %>  

   <div class="btn_menu"><p class="txtmenu"><%= link_to category.name, :action => 'index', :cat => category.id %></p>

	</div>
 <% end %>

app/views/categories/edit.html.erb
<DIV style="padding-left:200px; padding-top:10px;">
<h1>EDITAR CATEGORÍA</h1>
<table width="750px">
<tr>
	<td ><%= link_to 'Listado categorías', categories_path , :class => 'vermas'   %></td>
</tr>
<tr>
	<td>
<table>
 
<tr>
	<td>
	<%= render 'form' %>	
	</td>
</tr>

</table>
</td>
</tr>
</table>

app/views/categories/index.html.erb
<DIV style="padding-left:200px; padding-top:10px;">
<h1>LISTADO DE CATEGORÍAS </h1>


<table>
<tr>
	<td ><%= link_to 'Añadir categoría', new_category_path, :class => 'vermas'   %><</td>
</tr>
<tr>
	<td>
<table>
  <tr>
    <th>&nbsp;</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td class="texto" width="650px"><%= category.name %></td>
    <td></td>
    <td><%= link_to 'editar', edit_category_path(category), :class => 'vermas'  %></td>
    <td><%= link_to 'eliminar', category, :confirm => 'Estás seguro?', :method => :delete, :class => 'vermas'  %></td>
  </tr>
<% end %>
</table>
</td>
</tr>
</table>



<DIV>

app/views/categories/new.html.erb
<DIV style="padding-left:200px; padding-top:10px;">
<h1>CATEGORÍA NUEVA </h1>
<table width="750px">
<tr>
	<td ><%= link_to 'Listado categorías', categories_path , :class => 'vermas'   %></td>
</tr>
<tr>
	<td>
<table>
 
<tr>
	<td>
	<%= render 'form' %>	
	</td>
</tr>

</table>
</td>
</tr>
</table>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_file_name %><br />
    <%= f.text_field :image_file_name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :image_content_type %><br />
    <%= f.text_field :image_content_type %>
  </div>
  <div class="field">
    <%= f.label :image_file_size %><br />
    <%= f.text_field :image_file_size %>
  </div>
  <div class="field">
    <%= f.label :image_updated_at %><br />
    <%= f.datetime_select :image_updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Image file name</th>
    <th>Product</th>
    <th>Image content type</th>
    <th>Image file size</th>
    <th>Image updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.image_file_name %></td>
    <td><%= image.product_id %></td>
    <td><%= image.image_content_type %></td>
    <td><%= image.image_file_size %></td>
    <td><%= image.image_updated_at %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image file name:</b>
  <%= @image.image_file_name %>
</p>

<p>
  <b>Product:</b>
  <%= @image.product_id %>
</p>

<p>
  <b>Image content type:</b>
  <%= @image.image_content_type %>
</p>

<p>
  <b>Image file size:</b>
  <%= @image.image_file_size %>
</p>

<p>
  <b>Image updated at:</b>
  <%= @image.image_updated_at %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Laket Artesanos</title>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>

<body>
<div class="contenedor2">
  

<!-- cabecera -->
<div class="cabecera">
    <div class="menu">
    <ul>
    <li><a href="index.html">LAKET</a></li>
	 <li><a href="pnpspace.html">PRODUCTOS</a></li>
	 <li><a href="miembros.html">CANALES DE DISTRIBUCIÓN</a></li>
	 <li><a href="pnpschool.html">BLOG</a></li>
     <li><a href="pnpschool.html">CONTACTO</a></li>
    </ul>
    </div>
    <div class="iconos"><a href="https://www.facebook.com/profile.php?id=100002223007512" target="_blank"><img src="images/ico_facebook.png" width="63" height="64" /></a><img src="images/ico_twitter.png" width="63" height="64" /><img src="images/ico_rss.png" width="63" height="64" /></div>
</div>
<!-- fin cabecera -->
 

<div class="cuerpo">
 	
  <%= yield %>


</div>


<!--pie -->
<div class="pie">
  <a href="http://www.alimentosartesanos.com" target="_blank"><img src="images/logo_reyno.png" width="103" height="91" /><img src="images/logo_artesanos.png" width="92" height="94" /></a>
  
  <div class="creditos">
    <p class="txtcreditos">©2011 laket artesanos | Pol.Utzubar Calle E P-10 31839 Arbizu (Navarra)  | <a href="legoland">nota legal</a></p>
  </div> 
</div>
<!-- fin pie -->

</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nampeproduct %><br />
    <%= f.text_field :nampeproduct %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>





  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :expiration %><br />
    <%= f.text_area :expiration %>
  </div>
  <div class="field">
    <%= f.label :conservation %><br />
    <%= f.text_area :conservation %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.text_area :preparation %>
  </div>
  <div class="field">
    <%= f.label :mreinfo %><br />
    <%= f.text_area :mreinfo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_listado.html.erb
<!-- menu izquierda -->
  <div class="colleft2">
    <%  #render :partial => 'categories/categories', :controller => @categoriesr %>
    <% #render :partial => 'categories/categories', :locals => {:category => @categories} %>
    <% #render :partial=>'categories/categories', :collection => @categories %> 
 	<%= render :partial=>'categories/listado_edit', :controller => @categories %> 
  </div>
  <!-- fin menu izquierda -->


<!-- contenido --> 
  <div class="colright2">
      
	 <!-- titular -->
 	  <div class="titinterior2">
        <h1> NOVEDADES</h1>
      </div>
	 <!-- fin titular -->

     <!-- subtitulo --> 
	 <div class="subtitulo"><p class="txtmenu3">EMBUTIDOS</p>
      <a href="#" class="vermas">VER TODO</a></div>
     <!-- fin subtitulo -->


	  <% @products.each do |product| %>
	  <!-- lista producto -->
 	  <div class="listado">

 		<!-- producto -->
		<div class="img_listado">
	      <img src="images/img_portada.jpg" width="167" height="180" />
	      <div class="txt_listado">
            <p class="txtmenu2"><a href="#"><%= product.nampeproduct %></a></p>
          </div>
        </div>
        <!-- fin producto -->

      </div>
	  <!-- fin listado -->	
	  <% end %>
	
	
	
  </div>
  <!-- fin contenido -->


<h1>Listing products</h1>

<table>
  <tr>
    <th>Nampeproduct</th>
    <th>Category</th>
    <th>Ingredients</th>
    <th>Expiration</th>
    <th>Conservation</th>
    <th>Preparation</th>
    <th>Mreinfo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.nampeproduct %></td>
    <td><%= product.category_id %></td>
 <td><%= product.category %>  <% product.productsimages%></td>
    <td><%= product.ingredients %></td>
    <td><%= product.expiration %></td>
    <td><%= product.conservation %></td>
    <td><%= product.preparation %></td>
    <td><%= product.mreinfo %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% # will_paginate @products %>
<%= link_to 'New Product', new_product_path %>

app/views/products/_listado_edit.html.erb
<!-- menu izquierda -->
  <div class="colleft2">
    <%  #render :partial => 'categories/categories', :controller => @categoriesr %>
    <% #render :partial => 'categories/categories', :locals => {:category => @categories} %>
    <% #render :partial=>'categories/categories', :collection => @categories %> 
 	<%= render :partial=>'categories/listado_edit', :controller => @categories %> 
  </div>
  <!-- fin menu izquierda -->


<!-- contenido --> 
  <div class="colright2">
      
	 <!-- titular -->
 	  <div class="titinterior2">
        <h1> <%
if (@category!=nil)%>
<%= @category.name%>
<%end
 %></h1>
      </div>
	 <!-- fin titular -->

     


	  <% @products.each do |product| %>
	  <!-- lista producto -->
 	  <div class="listado">

 		<!-- producto -->
		<div class="img_listado">
			<%= link_to image_tag("images/img_portada.jpg"), product %>
			<%= link_to 'Show', product %>
			 
	      <div class="txt_listado">
            <p class="txtmenu2"><a href="#"><%= product.nampeproduct %></a></p>
          </div>
        </div>
        <!-- fin producto -->

      </div>
	  <!-- fin listado -->	
	  <% end %>
	<%= link_to 'New Product', new_product_path %>
	
	
  </div>
  <!-- fin contenido -->

app/views/products/_producto.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nampeproduct:</b>
  <%= @product.nampeproduct %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_id %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @product.ingredients %>
</p>

<p>
  <b>Expiration:</b>
  <%= @product.expiration %>
</p>

<p>
  <b>Conservation:</b>
  <%= @product.conservation %>
</p>

<p>
  <b>Preparation:</b>
  <%= @product.preparation %>
</p>

<p>
  <b>Mreinfo:</b>
  <%= @product.mreinfo %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/_producto_edit.html.erb
<!-- menu izquierda -->
  <div class="colleft2">
    <%  #render :partial => 'categories/categories', :controller => @categoriesr %>
    <% #render :partial => 'categories/categories', :locals => {:category => @categories} %>
    <% #render :partial=>'categories/categories', :collection => @categories %> 
 	<%= render :partial=>'categories/listado_edit', :controller => @categories %> 
  </div>
  <!-- fin menu izquierda -->


<!-- contenido --> 
  <div class="colright2">
      
	 <!-- titular -->
 	  <div class="titinterior2">
        <h1><%=  @product.category.name%></h1>
      </div>
	 <!-- fin titular -->

     


	
	
	
  </div>
  <!-- fin contenido -->




<p id="notice"><%= notice %></p>

<p>
  <b>Nampeproduct:</b>
  <%= @product.nampeproduct %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_id %>

</p>

<p>
  <b>Ingredients:</b>
  <%= @product.ingredients %>
</p>

<p>
  <b>Expiration:</b>
  <%= @product.expiration %>
</p>

<p>
  <b>Conservation:</b>
  <%= @product.conservation %>
</p>

<p>
  <b>Preparation:</b>
  <%= @product.preparation %>
</p>

<p>
  <b>Mreinfo:</b>
  <%= @product.mreinfo %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
 	<%= render :partial=>'listado_edit', :controller => @categories %> 

app/views/products/index2.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Nampeproduct</th>
    <th>Category</th>
    <th>Ingredients</th>
    <th>Expiration</th>
    <th>Conservation</th>
    <th>Preparation</th>
    <th>Mreinfo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.nampeproduct %></td>
    <td><%= product.category_id %></td>
 <td><%= product.category %>  <% product.productsimages%></td>
    <td><%= product.ingredients %></td>
    <td><%= product.expiration %></td>
    <td><%= product.conservation %></td>
    <td><%= product.preparation %></td>
    <td><%= product.mreinfo %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% # will_paginate @products %>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render :partial=>'producto_edit', :controller => @categories %> 